Solved
frontend-tinkoff-ekb/rtf-lab-2 pull request #11
Opened 2019-10-23 18:35 UTC by Akerlay

2019-10-24 08:07 UTC, ghost requested changes

2019-10-24 08:07 UTC, ghost commented on index.js
> +    return (...wrappedArgs) => func.apply(context, [].concat(args).concat(wrappedArgs));
args – уже массив.

2019-10-24 08:07 UTC, ghost commented on index.js
> +    if (!this.accumulator) {
Какое-то условие явно лишнее. Точно можно упростить примерно до вида – если пришло число, вернуть функцию, иначе – 0.

2019-11-05 09:31 UTC, AlexNg9 commented
@Akerlay правки будут?

2019-11-05 10:54 UTC, Akerlay commented
> @Akerlay правки будут?

Да, сегодня вечером откоммичу

2019-11-07 06:53 UTC, closed without merging