solution for 2nd lab
frontend-tinkoff-ekb/rtf-lab-2 pull request #15
Opened 2019-10-24 16:16 UTC by yakov-golencev

2019-10-24 17:42 UTC, yakov-golencev commented
я так понял что он жалуется на то что у меня args это string
но непонятно почему, потому что в функции args это массив сто процентов, а в методе непонятно на что жаловаться

2019-10-25 10:09 UTC, AlexNg9 commented
Это была моя ошибка в настройках тестового окружения, поправили.

2019-10-25 10:13 UTC, ghost requested changes

2019-10-25 10:13 UTC, AlexNg9 commented on index.js
> +        return customBind(finalResult, this, result + current);
Интересный ход мысли, но здесь выглядит усложнением.
Лучше рекурсивно вызвать finalResult.
Ниже аналогично.

2019-10-25 10:13 UTC, yakov-golencev commented
да, все в порядке, тетсы пройдены

2019-10-29 12:51 UTC, yakov-golencev commented on index.js
> +        return customBind(finalResult, this, result + current);
Готово

2019-10-31 11:46 UTC, ghost approved these changes

2019-10-31 11:46 UTC, AlexNg9 commented on index.js
> +    const sumRes = (current) => {
Можно сразу вернуть именованную функцию.

2019-10-31 11:46 UTC, AlexNg9 commented
👍

2019-10-31 11:46 UTC, closed without merging

2019-10-31 12:32 UTC, yakov-golencev commented
вы забыли поставить лейбл approved!