Update index.js
frontend-tinkoff-ekb/rtf-lab-2 pull request #28
Opened 2019-10-28 10:32 UTC by Komodood

Оба метода, Bind не проверял

2019-10-28 18:58 UTC, Komodood commented
Ура, восславим джаваскрипт и проверяющий
Я закончил

2019-10-30 06:47 UTC, ghost requested changes

2019-10-30 06:47 UTC, AlexNg9 commented on index.js
> +    let First = x;
Переменные с маленькой буквы.

2019-10-30 06:47 UTC, AlexNg9 commented on index.js
> +    return function BoyNextDoor (Next) {
Функции тоже.

2019-10-30 06:47 UTC, AlexNg9 commented on index.js
> +    let First = x;
Попробуйте переписать без этой переменной.

2019-10-30 22:10 UTC, Komodood commented on index.js
> +    return function BoyNextDoor (Next) {
Сделать все без переменных First и Next?

2019-10-31 06:45 UTC, AlexNg9 commented on index.js
> +    return function BoyNextDoor (Next) {
@Komodood без first, и назвать их правильно.

2019-11-05 09:29 UTC, ghost approved these changes
👍

2019-11-05 09:29 UTC, closed without merging