nu che pognali
frontend-tinkoff-ekb/rtf-lab-2 pull request #4
Opened 2019-10-23 14:06 UTC by DesperateHiking

2019-10-24 06:49 UTC, ghost requested changes

2019-10-24 06:49 UTC, AlexNg9 commented on index.js
> +        const inputArgs = [].slice.call(arguments);
Аргументы можно собрать прямо в сигнатуре функции.

2019-10-24 06:49 UTC, AlexNg9 commented on index.js
> + * sum(1)(2)(3)(4)( ) // 10
Тоже верно.

2019-10-24 06:49 UTC, AlexNg9 commented on index.js
> +let accumulator = 0;
То, что переменная доступна вне функции – плохо. К ней можно будет обратиться из других функций. Нужно ее как-то спрятать.

2019-10-24 16:42 UTC, DesperateHiking commented
как-то тупо коммит назвал, больше так не буду

2019-10-25 07:24 UTC, ghost requested changes

2019-10-25 07:24 UTC, AlexNg9 commented on index.js
> +    const accumulator = [];
Зачем массив? Почему не через число?

2019-10-25 08:02 UTC, DesperateHiking commented on index.js
> +    const accumulator = [];
сейчас все будет((

2019-10-25 08:13 UTC, DesperateHiking commented on index.js
> +    const accumulator = [];
а вообще просто захотелось что-то нетакое как у всех сделать
![cD8dxkoOYFA](https://user-images.githubusercontent.com/48237694/67554605-2a7bff80-f729-11e9-98b3-4c7feafce44f.jpg)

2019-10-25 08:24 UTC, AlexNg9 commented on index.js
> +    const accumulator = [];
@desperateHiking, окей, понял
Но это избыточно все-таки

2019-10-25 08:26 UTC, ghost approved these changes
🚀

2019-10-25 08:26 UTC, AlexNg9 commented on index.js
> +        return sum(x + nextNum);
Вот это очень хороший вариант. Даже дополнительную переменную не нужно создавать.

2019-10-25 08:28 UTC, closed without merging